#!/usr/bin/env bash
# embed_html.sh — Convert index.html into a C header (index_html.h)
# Usage: bash embed_html.sh [input.html] [output.h]
#   Defaults: input = index.html, output = index_html.h

set -euo pipefail

INPUT="${1:-index.html}"
OUTPUT="${2:-index_html.h}"

if [ ! -f "$INPUT" ]; then
    echo "ERROR: '$INPUT' not found." >&2
    exit 1
fi

# Escape backslashes, double quotes, and newlines for a C string literal.
# Then write out a header with the string and its length.
{
    echo "/* Auto-generated by embed_html.sh — do not edit */"
    echo "#ifndef INDEX_HTML_H"
    echo "#define INDEX_HTML_H"
    echo ""
    echo "const char index_html[] ="
    # Process line-by-line; each line is wrapped in quotes and joined with \n
    first=1
    while IFS= read -r line || [ -n "$line" ]; do
        if [ "$first" -eq 1 ]; then
            printf '"%s\\n"' "$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g')"
            first=0
        else
            printf '"%s\\n"' "$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g')"
        fi
    done < "$INPUT"
    echo ";"
    echo ""
    echo "const size_t index_html_len = sizeof(index_html) - 1;"
    echo ""
    echo "#endif // INDEX_HTML_H"
} > "$OUTPUT"

echo "Embedded '$INPUT' → '$OUTPUT' ($(wc -c < "$INPUT") bytes)"
